const constants = {
    CONST_PRODUCT_PER_PAGE:5,
    CONST_USER_PER_PAGE:5,
    CONST_ORDER_PER_PAGE:5,
    CONST_CATEGORY_PER_PAGE:5,
    CONST_ORDER_STATUS_ORDERED:"0",
    CONST_ORDER_STATUS_WATTING_FOR_PAYMENT:"1",
    CONST_ORDER_STATUS_ACCEPTED:"2",
    CONST_ORDER_STATUS_SHIPPING:"3",
    CONST_ORDER_STATUS_SHIPPED:"4",
    CONST_ORDER_STATUS_COMPLETE:"5",
    CONST_ORDER_STATUS_ORDERED_TEXT:"Ordered",
    CONST_ORDER_STATUS_WATTING_FOR_PAYMENT_TEXT:"Wait for payment",
    CONST_ORDER_STATUS_ACCEPTED_TEXT:"Accepted",
    CONST_ORDER_STATUS_SHIPPING_TEXT:"Shipping",
    CONST_ORDER_STATUS_SHIPPED_TEXT:"Shipped",
    CONST_ORDER_STATUS_COMPLETE_TEXT:"Complete",
}

export default constants